sudo: required
services:
  - docker

before_install:
 - docker build -t amohamedd74/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amohamedd74/react-test npm test -- --coverage

after_success:
  - docker build -t amohamedd74/multi-client ./client
  - docker build -t amohamedd74/multi-nginx ./nginx
  - docker build -t amohamedd74/multi-server ./server
  - docker build -t amohamedd74/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push amohamedd74/multi-client
  - docker push amohamedd74/multi-nginx
  - docker push amohamedd74/multi-server
  - docker push amohamedd74/multi-worker